import { Component, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-about', imports: [FormsModule],
  template: `
    <section class="about-hero"><div class="container about-hero-grid"><div><span class="eyebrow">Nuestra historia</span><h1>La curiosidad<br>es un <em>superpoder.</em></h1><p>Nacimos con una pregunta simple: ¿y si aprender se sintiera tan emocionante como descubrir un mundo nuevo?</p></div><div class="about-collage"><div class="collage-main">🧠<span>✦</span></div><div class="collage-note">Desde 2022<br><strong>jugando en serio.</strong></div><div class="collage-stat"><strong>32k+</strong><span>mentes curiosas</span></div></div></div></section>
    <section class="story section"><div class="container story-grid"><div><span class="eyebrow">Por qué existimos</span><h2>Del salón de clases<br>a una <em>gran aventura</em></h2></div><div><p class="lead">BrainBoost comenzó cuando una maestra, un diseñador de juegos y una mamá decidieron que practicar no tenía por qué sentirse como obligación.</p><p>En 2022 creamos nuestro primer prototipo con un grupo de 18 estudiantes en Ciudad de México. Sus preguntas y risas nos enseñaron el camino: retos breves, historias memorables y espacio para equivocarse.</p><p>Hoy colaboramos con educadores y familias para convertir conceptos esenciales en experiencias que construyen confianza de verdad.</p></div></div></section>
    <section class="mission section"><div class="container mission-grid"><div class="mission-card"><span>✦</span><small>Nuestra misión</small><h2>Encender la chispa de aprender para toda la vida.</h2><p>Diseñamos experiencias seguras, inclusivas y llenas de propósito que ayudan a cada niño a descubrir de lo que es capaz.</p></div><div class="values"><article><b>01</b><div><h3>Curiosidad primero</h3><p>Las mejores respuestas comienzan con una buena pregunta.</p></div></article><article><b>02</b><div><h3>Jugar con propósito</h3><p>Cada reto divierte y también desarrolla una habilidad real.</p></div></article><article><b>03</b><div><h3>Confianza para crecer</h3><p>Celebramos el progreso, no la perfección.</p></div></article></div></div></section>
    <section class="team section"><div class="container"><div class="section-heading split"><div><span class="eyebrow">Las mentes detrás</span><h2>Un equipo que nunca<br>dejó de <em>preguntar</em></h2></div><p>Educadores, narradores y creadores de juego unidos por una misma misión.</p></div><div class="team-grid"><article><div class="team-avatar avatar-one">👩🏽‍🏫</div><span>Co-fundadora · Educación</span><h3>Valeria Cruz</h3><p>Maestra y especialista en aprendizaje, convierte objetivos pedagógicos en momentos “¡ajá!”.</p></article><article><div class="team-avatar avatar-two">👨🏻‍💻</div><span>Co-fundador · Producto</span><h3>Diego Mendoza</h3><p>Diseñador de juegos que cree que una interfaz también puede contar una gran historia.</p></article><article><div class="team-avatar avatar-three">👩🏿‍🎨</div><span>Dirección creativa</span><h3>Amara Okafor</h3><p>Ilustradora y narradora, da vida a los mundos que hacen memorable cada reto.</p></article><article><div class="team-avatar avatar-four">👨🏽‍🔬</div><span>Contenido · Ciencias</span><h3>Leo Salas</h3><p>Divulgador científico obsesionado con explicar lo complejo de forma irresistible.</p></article></div></div></section>
    <section class="contact-section section" id="contacto"><div class="container contact-grid"><div><span class="eyebrow light">Hablemos</span><h2>¿Tienes una idea,<br>pregunta o <em>reto?</em></h2><p>Nos encantará leerte. Respondemos normalmente en menos de dos días hábiles.</p><div class="contact-details"><a href="mailto:hola@brainboost.mx">hola&#64;brainboost.mx</a><span>Ciudad de México, México</span></div></div><form (ngSubmit)="submit()"><label>Nombre<input [(ngModel)]="name" name="name" required placeholder="Tu nombre"></label><label>Correo electrónico<input [(ngModel)]="email" name="email" type="email" required placeholder="tu@correo.com"></label><label>¿En qué podemos ayudarte?<select [(ngModel)]="subject" name="subject"><option>Familia interesada</option><option>Escuela o docente</option><option>Alianza</option><option>Soporte</option></select></label><label>Mensaje<textarea [(ngModel)]="message" name="message" required placeholder="Cuéntanos un poco más..."></textarea></label><button class="button button-primary" type="submit">Enviar mensaje →</button>@if (sent()) {<p class="form-success">✓ ¡Gracias! Tu mensaje está en camino.</p>}</form></div></section>
  `,
})
export class AboutComponent {
  name = ''; email = ''; subject = 'Familia interesada'; message = ''; readonly sent = signal(false);
  submit() { this.sent.set(true); this.name = ''; this.email = ''; this.message = ''; }
}

